openapi: 3.0.2
info:
  title: "APIxEformidling"
  version: "1.0.0"
paths: 
  /capabilities:
    get:
      summary: "Get capabilities"
      description: "The service is used to get capabilities for a receiver"
      responses:
        "200":
          description: "Ok"
  /messages/in:
    get:
      summary: "Find incoming messages"
      description: "The service is used to search for incoming messages. The response is paged with a default page size of 10."
      responses:
        "200":
          description: "Ok"
  /messages/in/peek:
    get:
      summary: "Peek incoming message"
      description: ""
      responses:
        "200":
          description: "Ok"
  /messages/in/pop/{messageId}:
    get:
      summary: "Pop incoming message"
      description: ""
      parameters:
      - name: messageId
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
  /messages/in/{messageId}:
    delete:
      summary: "Delete incomig message"
      description: ""
      parameters:
      - name: messageId
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "Ok"
  /messages/out:
    post:
      summary: "Create message"
      description: ""
      responses:
        "200":
          description: "Ok"
    get:
      summary: "Find outgoing messages"
      description: ""
      responses:
        "200":
          description: "Ok"
  /messages/out/{messageId}:
    get:
      summary: "Get outgoing message"
      description: ""
      parameters:
      - name: messageId
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
    put:
      summary: "Upload attachment"
      description: ""
      parameters:
      - name: messageId
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
    delete:
      summary: "Delete message"
      parameters:
      - name: messageId
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
    post: 
      summary: "Send message"
      parameters:
      - name: messageId
        in: path
        required: true
        schema:
            type: string
      description: ""
      responses:
        "200":
          description: "Ok"
  /messages/out/multipart:
    post:
      summary: "Send multipart message"
      responses:
        "200":
          description: "Ok"
  /conversations:
    get:
      summary: "Find conversations"
      description: ""
      responses:
        "200":
          description: "Ok"
  /conversations/{id}:
    get:
      summary: "Get conversation by Id"
      description: ""
      parameters:
      - name: id
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
  /conversations/messageId/{messageId}:
    get:
      summary: "Get conversation by messageId"
      description: ""
      parameters:
      - name: messageId
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
  /conversations/queue:
    get:
      summary: "Queued conversations"
      responses:
        "200":
          description: "Ok"
  /statuses:
    get:
      summary: "Get message statuses"
      responses:
        "200":
          description: "Ok"
  /statuses/{messageId}:
    get:
      summary: "Find message statuses by messageId"
      parameters:
      - name: messageId
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
  /statuses/peek:
    get:
      summary: "Peek the lastest message status"
      responses:
        "200":
          description: "Ok"
  /subscriptions:
    get:
      summary: "Get subscriptions"
      responses:
        "200":
          description: "Ok"
    post: 
      summary: "Create a subscription"
      responses:
        "200":
          description: "Ok"
    delete:
      summary: "Delete all subscriptions"
      responses:
        "200":
          description: "Ok"
  /subscriptions/{id}:
    post:
      summary: "Get a subscription"
      parameters:
      - name: id
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
    delete: 
      summary: "Delete a subscription"
      parameters:
      - name: id
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
    put:
      summary: "Update a subscription"
      parameters:
      - name: id
        in: path
        required: true
        schema:
            type: string
      responses:
        "200":
          description: "Ok"
  /manage/health:
    get:
      summary: "Returns status"
      responses:
        "200":
          description: "Ok"